# .github/workflows/gradle-build-pr.yml
name: Run Gradle on PRs
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        task: [integrationTest, docTest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    #run the build
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: ${{ matrix.task }}
    #upload build reports for later inspection
    - uses: actions/upload-artifact@v2
      # if: failure()
       with:
        name: testreports
        path: build/reports/tests